<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>MusicLibrary</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="TodoApp.Tests\" />
  </ItemGroup>



</Project>
